name: invokeai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.2.2
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy=1.23
  - imageio=2.21
  - opencv=4.6
  - pillow=8.*
  - flask=2.1.*
  - flask_cors=3.0.10
  - flask-socketio=5.3.0
  - send2trash=1.8.0
  - eventlet
  - albumentations=0.4.3
  - pudb=2019.2
  - imageio-ffmpeg=0.4.2
  - pytorch-lightning=1.7.7
  - streamlit
  - einops=0.3.0
  - kornia=0.6
  - torchmetrics=0.7.0
  - transformers=4.23
  - torch-fidelity=0.3.0
  - tokenizers>=0.11.1,!=0.11.3,<0.13
  - pip:
      - dependency_injector==4.40.0
      - getpass_asterisk
      - omegaconf==2.1.1
      - pyreadline3
      - taming-transformers-rom1504
      - test-tube>=0.7.5
      - git+https://github.com/openai/CLIP.git@main#egg=clip
      - git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k_diffusion
      - git+https://github.com/invoke-ai/Real-ESRGAN.git#egg=realesrgan
      - git+https://github.com/invoke-ai/GFPGAN.git#egg=gfpgan
      - git+https://github.com/invoke-ai/clipseg.git@models-rename#egg=clipseg
      - -e .
