stable-diffusion-2.1:
   description: Stable Diffusion version 2.1 diffusers model (5.21 GB)
   repo_id: stabilityai/stable-diffusion-2-1
   format: diffusers
   recommended: True
stable-diffusion-1.5:
   description: Stable Diffusion version 1.5 weight file (4.27 GB)
   repo_id: runwayml/stable-diffusion-v1-5
   format: diffusers
   recommended: True
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   width: 512
   height: 512
inpainting-1.5:
   description: RunwayML SD 1.5 model optimized for inpainting (4.27 GB)
   repo_id: runwayml/stable-diffusion-inpainting
   format: diffusers
   recommended: True
   width: 512
   height: 512
stable-diffusion-1.4:
   description: The original Stable Diffusion version 1.4 weight file (4.27 GB)
   repo_id: CompVis/stable-diffusion-v1-4
   recommended: False
   format: diffusers
   vae:
      repo_id: stabilityai/sd-vae-ft-mse
   width: 512
   height: 512
waifu-diffusion-1.3:
   description: Stable Diffusion 1.4 fine tuned on anime-styled images (4.27 GB)
   repo_id: hakurei/waifu-diffusion-v1-3
   config: v1-inference.yaml
   file: model-epoch09-float32.ckpt
   format: ckpt
   vae:
      repo_id: stabilityai/sd-vae-ft-mse-original
      file: vae-ft-mse-840000-ema-pruned.ckpt
   recommended: False
   width: 512
   height: 512
trinart-2.0:
   description: An SD model finetuned with ~40,000 assorted high resolution manga/anime-style pictures (2.13 GB)
   repo_id: naclbit/trinart_stable_diffusion_v2
   format: diffusers
   recommended: False
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   width: 512
   height: 512
trinart_characters-2.0:
   description: An SD model finetuned with 19.2M anime/manga style images (4.27 GB)
   repo_id: naclbit/trinart_derrida_characters_v2_stable_diffusion
   config: v1-inference.yaml
   file: derrida_final.ckpt
   format: ckpt
   vae:
      repo_id: naclbit/trinart_derrida_characters_v2_stable_diffusion
      file: autoencoder_fix_kl-f8-trinart_characters.ckpt
   recommended: False
   width: 512
   height: 512
papercut-1.0:
   description: SD 1.5 fine-tuned for papercut art (use "PaperCut" in your prompts) (2.13 GB)
   repo_id: Fictiverse/Stable_Diffusion_PaperCut_Model
   format: diffusers
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   recommended: False
   width: 512
   height: 512
voxel_art-1.0:
   description: Stable Diffusion trained on voxel art (use "VoxelArt" in your prompts) (4.27 GB)
   repo_id: Fictiverse/Stable_Diffusion_VoxelArt_Model
   config: v1-inference.yaml
   file: VoxelArt_v1.ckpt
   format: ckpt
   vae:
     repo_id: stabilityai/sd-vae-ft-mse
   recommended: False
   width: 512
   height: 512
ft-mse-improved-autoencoder-840000:
   description: StabilityAI improved autoencoder fine-tuned for human faces. Use with legacy .ckpt models ONLY (335 MB)
   repo_id: stabilityai/sd-vae-ft-mse-original
   format: ckpt
   config: VAE/default
   file: vae-ft-mse-840000-ema-pruned.ckpt
   recommended: False
   width: 512
   height: 512
trinart_vae:
   description: Custom autoencoder for trinart_characters for legacy .ckpt models only (335 MB)
   repo_id: naclbit/trinart_characters_19.2m_stable_diffusion_v1
   config: VAE/trinart
   format: ckpt
   file: autoencoder_fix_kl-f8-trinart_characters.ckpt
   recommended: False
   width: 512
   height: 512
