name: invokeai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - albumentations=0.4.3
  - cudatoolkit
  - einops=0.3.0
  - eventlet
  - flask-socketio=5.3.0
  - flask=2.1.*
  - flask_cors=3.0.10
  - imageio-ffmpeg=0.4.2
  - imageio=2.9.0
  - kornia=0.6
  - numpy=1.19
  - opencv=4.6.0
  - pillow=8.*
  - pip>=22.2.2
  - pudb=2019.2
  - python=3.9.*
  - pytorch
  - pytorch-lightning=1.7.7
  - send2trash=1.8.0
  - streamlit
  - tokenizers>=0.11.1,!=0.11.3,<0.13
  - torch-fidelity=0.3.0
  - torchmetrics=0.7.0
  - torchvision
  - transformers=4.21.3
  - pip:
      - dependency_injector==4.40.0
      - getpass_asterisk
      - omegaconf==2.1.1
      - picklescan
      - pyreadline3
      - realesrgan
      - taming-transformers-rom1504
      - test-tube>=0.7.5
      - https://github.com/TencentARC/GFPGAN/archive/refs/tags/v1.3.8.zip#egg=gfpgan
      - https://github.com/Birch-san/k-diffusion/archive/refs/tags/v0.0.10.zip#egg=k-diffusion
      - https://github.com/invoke-ai/PyPatchMatch/archive/refs/tags/0.1.4.zip#egg=pypatchmatch
      - https://github.com/openai/CLIP/archive/eaa22acb90a5876642d0507623e859909230a52d.zip#egg=clip
      - https://github.com/invoke-ai/clipseg/archive/relaxed-python-requirement.zip#egg=clipseg
      - -e .
